spring:
  application:
    name: AutenticationService
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: C##servAuth
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: chat4metest@gmail.com
    sender: chat4metest@gmail.com
    password: yduq auzx hmjy apjw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  app:
    jwtAccessCookieName: jwtAccessCookie
    jwtRefreshCookieName: jwtRefreshCookie
    jwtSecret: PeroquantoatequellochepuifarechetupertequalcosadapoterfaredovrebbeesserciNonticostringeranessunoPensadatestodecididatestochecosaadessotutestessodebbafare
    jwtAccessExpirations: 60000
    jwtRefreshExpirations: 604800000
