package com.example.autenticationservice.application.mapper;

import com.example.autenticationservice.domain.model.NewAccessTokenByRefreshToken.FirstStepNewAccessTokenByRefreshTokenRequest;
import com.example.autenticationservice.domain.model.NewAccessTokenByRefreshToken.FirstStepNewAccessTokenByRefreshTokenResponse;
import com.example.autenticationservice.generated.application.model.RefreshToken200Response;
import com.example.autenticationservice.generated.application.model.RefreshTokenRequest;
import org.mapstruct.Mapper;

@Mapper
public interface NewAccessTokenByRefreshTokenMappers {
    FirstStepNewAccessTokenByRefreshTokenRequest convertToDomain(RefreshTokenRequest refreshTokenRequest);
    RefreshToken200Response convertFromDomain(FirstStepNewAccessTokenByRefreshTokenResponse firstStepNewAccessTokenByRefreshTokenResponse);
}
